### ISSUE TITLE
on localhost

### ISSUE THREAD

**Issue by boyfromhell** [lbausch/flarum-laravel-session#2]
Install on localhost

Laravel on laravel.test
Flarum on flarum.laravel.test

On laravel site get error 403

**Comment by lbausch** [comment]
@boyfromhell This means that either the request contains no Flarum session cookie or a user could not be found in the user table of the Flarum database.
Can you try to use `.laravel.test` as the cookie domain for Flarum as outlined in the readme?

**Comment by boyfromhell** [comment]
@lbausch now have this error
`Target [Bausch\FlarumLaravelSession\Contracts\FlarumUserIdentified] is not instantiable.`

update to laravel 8

//edit 

`FlarumLaravelSession::handleIdentifiedUser(HandleIdentifiedUser::class);`

//edit 2

how to logout from laravel whem logout from forum?

**Comment by lbausch** [comment]
This is something you would have to do manually for now.
